// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

#include <OB/CORBAServer.h>
#include <apptest_skel.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4000500L)
#       error ORBacus version mismatch!
#   endif
#endif

//
// IDL:AppTest:1.0
//

//
// IDL:AppTest/Testing/say:1.0
//
void
POA_AppTest::Testing::_OB_op_say(OB::Upcall_ptr _ob_up)
{
    OB::StrForStruct _ob_a0;
    OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_up);
    _ob_a0 = _ob_in -> read_string();
    _OB_postUnmarshal(_ob_up);
    say(_ob_a0);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:AppTest/Testing:1.0
//
CORBA::Boolean
POA_AppTest::Testing::_is_a(const char* type)
    throw(CORBA::SystemException)
{
    const char** _ob_ids = AppTest::Testing::_OB_staticIds();
    for(CORBA::ULong _ob_i = 0 ; _ob_ids[_ob_i] != 0 ; _ob_i++)
        if(strcmp(type, _ob_ids[_ob_i]) == 0)
            return true;

    return false;
}

CORBA::RepositoryId
POA_AppTest::Testing::_primary_interface(const PortableServer::ObjectId&,
                                         PortableServer::POA_ptr)
{
    return CORBA::string_dup(AppTest::Testing::_OB_staticIds()[0]);
}

AppTest::Testing_ptr
POA_AppTest::Testing::_this()
{
    CORBA::Object_var obj = _OB_createReference();
    AppTest::Testing_var result = AppTest::Testing::_narrow(obj);
    return result._retn();
}

OB::DirectStubImpl_ptr
POA_AppTest::Testing::_OB_createDirectStubImpl(PortableServer::POA_ptr poa,
                                               const PortableServer::ObjectId& oid)
{
    return new OBDirectStubImpl_AppTest::Testing(poa, oid, this);
}

void
POA_AppTest::Testing::_OB_dispatch(OB::Upcall_ptr _ob_up)
{
    static const char* _ob_names[] =
    {
        "say"
    };
    static const CORBA::ULong _ob_numNames = 1;

    switch(_OB_findOperation(_ob_up, _ob_names, _ob_numNames))
    {
    case 0: // say
        _OB_op_say(_ob_up);
        return;
    }

    _OB_dispatchBase(_ob_up);
}

//
// IDL:AppTest/Testing:1.0
//
OBDirectStubImpl_AppTest::Testing::Testing(PortableServer::POA_ptr poa,
                                           const PortableServer::ObjectId& oid,
                                           PortableServer::ServantBase* servant)
#ifdef HAVE_VCPLUSPLUS_BUGS
{
    initialize(poa, oid, servant);
}
#else
    : OB::DirectStubImpl(poa, oid, servant)
{
}
#endif

//
// IDL:AppTest/Testing/say:1.0
//
void
OBDirectStubImpl_AppTest::Testing::say(const char* _ob_a0)
{
    OB::InvocationHandler _ob_handler(this, "say");
    dynamic_cast<POA_AppTest::Testing*>(_ob_servant_) -> say(_ob_a0);
}
